
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUAL ID LBRACKET NEWLINE RBRACKET VALUE\n    program : statements\n    \n    statements : statement\n               | statements statement\n    \n    statement : LBRACKET ID RBRACKET NEWLINE\n    \n    statement : ID EQUAL VALUE NEWLINE\n    \n    statement : NEWLINE\n    '
    
_lr_action_items = {'LBRACKET':([0,2,3,6,7,12,13,],[4,4,-2,-6,-3,-4,-5,]),'ID':([0,2,3,4,6,7,12,13,],[5,5,-2,8,-6,-3,-4,-5,]),'NEWLINE':([0,2,3,6,7,10,11,12,13,],[6,6,-2,-6,-3,12,13,-4,-5,]),'$end':([1,2,3,6,7,12,13,],[0,-1,-2,-6,-3,-4,-5,]),'EQUAL':([5,],[9,]),'RBRACKET':([8,],[10,]),'VALUE':([9,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','test.py',55),
  ('statements -> statement','statements',1,'p_statements_list','test.py',62),
  ('statements -> statements statement','statements',2,'p_statements_list','test.py',63),
  ('statement -> LBRACKET ID RBRACKET NEWLINE','statement',4,'p_statement_section','test.py',70),
  ('statement -> ID EQUAL VALUE NEWLINE','statement',4,'p_statement_key_value','test.py',80),
  ('statement -> NEWLINE','statement',1,'p_statement_newline_only','test.py',95),
]
